server:
  port: 8080
spring:
  application:
    name: SkyVoucher
  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/skyvoucher?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  # redis
  redis:
    host: 192.168.220.128
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
rocketmq:
  name-server: 192.168.220.128:9876
  producer:
    group: seckillgroup
    send-message-timeout: 3000

